export const SHOW_DIALOG_CONTENT = "[dialog] SHOW DIALOG CONTENT";
export const SHOW_DIALOG_CONTENT_SUCCESS = "[dialog] SHOW DIALOG CONTENT SUCCESS";

export const DIALOG_CHANGE_SETTINGS = "[dialog] DIALOG CHANGE SETTINGS";
export const DIALOG_CHANGE_SETTINGS_SUCCESS = "[dialog] DIALOG CHANGE SETTINGS SUCCESS";